### ISSUE TITLE
FIRE breaks chat with blur

### ISSUE THREAD

**Issue by GolfingSuccess** [Charcoal-SE/userscripts#127] opened 2018-08-10 19:35 UTC
![Right side disappeared after opening FIRE with blur enabled.](https://user-images.githubusercontent.com/19519588/43977446-e1ab061c-9cec-11e8-8aa2-69015151bd2e.png "Where are the users?") 

When blur is enabled, the whole right side of chat disappears. On top of that, I've noticed that, when a message gets posted, the whole chat gets scrolled down for a fraction of a second, not just the message area.

The issue disappears after blur is disabled or the FIRE window is closed.

**Priority note**: This isn't as important as some other issues can be, as the issue is only graphical, and the FIRE window itself is pretty clear.

**Comment by makyen** [comment] 2018-10-10 00:10
Duplicate of #98.

**Closed** 2018-10-10 00:11 UTC
Labels: FIRE, duplicate
